# Generated by Django 4.2.7 on 2024-08-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('instrument_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alb_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('musicians', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.musicians')),
            ],
        ),
    ]
