# Generated by Django 5.0.6 on 2024-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
