# Generated by Django 5.0.6 on 2024-08-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('categories', '0001_initial'),
        ('posts', '0002_alter_posts_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
